version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning #--requirepass euOX7EwVmmxKdayKBTsy354p
    volumes:
      - cache:/data
  # api:
  #   container_name: quotes-api
  #   build:
  #     context: ./
  #     target: production
  #   image: quotes-api
  #   depends_on:
  #     - db
  #     - cache
  #   ports:
  #     - 3000:3000
  #   environment:
  #     NODE_ENV: production
  #     REDIS_HOST: cache
  #     REDIS_PORT: 6379
  #     REDIS_PASSWORD: euOX7EwVmmxKdayKBTsy354p
  #   links:
  #     - db
  #     - cache
  #   volumes:
  #     - ./:/src
volumes:
  cache:
    driver: local